set shell=/bin/bash
source ~/dotfile/src/vundle_files.vim
source ~/dotfile/src/setting.vim
source ~/dotfile/src/syntax.vim
source ~/dotfile/src/tab.vim
source ~/dotfile/src/search.vim
source ~/dotfile/src/map.vim
source ~/dotfile/src/appearance.vim
source ~/dotfile/src/clipboard.vim
source ~/dotfile/src/nerdtree.vim
source ~/dotfile/src/neocomplete.vim
source ~/dotfile/src/neosnippet.vim
source ~/dotfile/src/tags.vim
